version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - application-network

networks:
  application-network:
    external: true