version: "3.9"
services:
  eureka-server:
    container_name: api-gateway
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8891:8891"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - application-network

networks:
  application-network:
    external: true