server:
  port: 8891
spring:
  application:
    name: api-gateway
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maurolisena/config-repo
    discovery:
      enabled: true
      eureka:
        client:
          register-with-eureka: true
          fetch-registry: true
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/